Sport/dashboard/urls.py
from django.urls import path, re_path
from . import views
from .data_generator import insert_data
from . import dash_app_base_generic   # this loads the Dash app
from . import dash_layouts
from .dash_server import app, server


app_name = 'dashboard'

urlpatterns = [
                re_path('^_dash-', views.dash_ajax),
                path('index/', views.index, name='index'),
                path('<author_id>/team/', views.dashboard1, name='team'),
                path('<author_id>/player/', views.dashboard2, name='player'),
                path('livingstream/', views.livingstream, name='livingstream'),
              ]

Sport/website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

# Use static() to add url mapping to serve static files during development (only)
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    #admin
    path('admin/', admin.site.urls),

    # app:
    path('dashboard/', include('dashboard.urls')),
    # end of urls list. append static doc folder:
    ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Sport/dashboard/models.py
from django.db import models

class Author(models.Model):
    name = models.CharField(max_length=100)

Sport/dashboard/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import Author
from .dash_server import dash_dispatcher, clean_dash_content
from django.views.decorators.csrf import csrf_exempt
from .data_generator import insert_data

def index(request):

    # get the list of engagements:
    authors = Author.objects.all()

    # get dash content:
    #print(authors)

    context = {'authors': authors}

    return render(request, 'index.html', context=context)

@csrf_exempt
def dash_ajax(request, **kwargs):
    print('Function: dash_ajax')
    return HttpResponse(dash_dispatcher(request,), content_type='application/json')


def dashboard1(request, author_id):
    authors = Author.objects.all()

    # get the django context:
    #author = get_object_or_404(Author, pk=author_id)

    print("Function: dash_django_page(): Getting 'dash_content'")
    dash_content = HttpResponse(dash_dispatcher(request,), content_type='application/json').getvalue()

    # clean the dash html content (the content contains lots of unnecessary characters like '\n')
    dash_content = clean_dash_content(dash_content)
    context = {'authors': authors, 'dash_content': dash_content}

    return render(request, 'dash.html', context=context)


def dashboard2(request, author_id):
    authors = Author.objects.all()

   # context = {'authors': authors[0]}

    # get the django context:
   # author = get_object_or_404(Author, pk=author_id)

    print("Function: dash_django_page(): Getting 'dash_content'")
    dash_content = HttpResponse(dash_dispatcher(request,), content_type='application/json').getvalue()

    # clean the dash html content (the content contains lots of unnecessary characters like '\n')
    dash_content = clean_dash_content(dash_content)
    context = {'authors': authors, 'dash_content': dash_content}

    return render(request, 'dash.html', context=context)


@csrf_exempt
def livingstream(request):
    if request.is_ajax():
        print("check,check")
        insert_data()

    return HttpResponse('success')

Sport/dashboard/templates/base.html
{% load static %}
import dash_core_components as dcc
import dash_html_components as html
from .models import Author
from django.shortcuts import get_object_or_404
import pandas as pd
import plotly.graph_objs as go
import numpy as np


<!DOCTYPE html>
<html lang="en">
<head>
  {% block title %}<title>Axicor Sport Analytics</title>{% endblock %}
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <link href="{% static 'dashboard/bootstrap.min.css' %}" rel="stylesheet">
  <script src="{% static 'dashboard/jquery.min.js' %}"></script>
  <script src="{% static 'dashboard/bootstrap.min.js' %}"></script>

  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>

  <!-- Add additional CSS in static file -->
  <link href="{% static 'dashboard/react-select@1.0.0-rc.3.min.css' %}" rel="stylesheet">
  <link href="{% static 'dashboard/custom_dash_styles.css' %}" rel="stylesheet">
</head>


<body>
<h1>Django Website</h1>
    <div class="col-sm-12">
      {% block content %}{% endblock %}
    </div>
</body>
</html>

Sport/dashboard/templates/dashboard1.html
{% extends "base.html" %}

{% block content %}

      <br>
      <h4>About Author: {{author.name}} </h4>

      <p>Cupcake ipsum dolor sit amet tootsie roll lemon drops. Marzipan gummi bears wafer. Jujubes topping sesame snaps oat cake gummies. Tootsie roll tootsie roll jelly-o dessert croissant</p> <br>

      <a href="{% url 'dashboard:index' %}">Go Back</a> </td>

      <div>

            {{ dash_content | safe}}


      </div>

{% endblock %}

Sport/dashboard/templates/dashboard2.html
{% extends "base.html" %}

{% block content %}

      <br>
      <h4>About Author: {{author.name}} </h4>

      <p>Cupcake ipsum dolor sit amet tootsie roll lemon drops. Marzipan gummi bears wafer. Jujubes topping sesame snaps oat cake gummies. Tootsie roll tootsie roll jelly-o dessert croissant</p> <br>

      <a href="{% url 'dashboard:index' %}">Go Back</a> </td>

      <div>

            {{ dash_content | safe}}

      </div>

{% endblock %}

Sport/dashboard/templates/index.html
{% extends "base.html" %}

{% block content %}

<table style='width: 1000px'>

    <tr>
        <th>ID</th>
        <th>Author Name</th>
        <th>Link</th>

    {% for author in authors %}

      <tr>
        <td> {{ author.id }} </td>
        <td> {{ author.name }} </td>
        <td>  <a href="{% url 'dashboard:team' author.id %}">Go to Dash </a>
      </tr>
    {% endfor %}

</table>

{% endblock %}